{ $Id$ }

const
  LINEFEEDSTRING = #13#10;

const
  MOUSE_LEFT   = 1;
  MOUSE_RIGHT  = 2;
  MOUSE_MIDDLE = 4;

const
  UserNamedColorStart = 128;

// named color identifiers
const
  clWindowBackground     = $80000001;
  clBoxColor             = $80000002;

  clButtonFace           = $80000003;

  clShadow1              = $80000004;
  clShadow2              = $80000005;
  clHilite1              = $80000006;
  clHilite2              = $80000007;

  clText1                = $80000008;
  clText2                = $80000009;
  clText3                = $8000000A;
  clText4                = $8000000B;

  clSelection            = $8000000C;
  clSelectionText        = $8000000D;

  clInactiveSel          = $8000000E;
  clInactiveSelText      = $8000000F;

  clScrollBar            = $80000010;

  clListBox              = $80000011;

  clGridLines            = $80000012;
  clGridHeader           = $80000013;

  clWidgetFrame          = $80000014;
  clInactiveWgFrame      = $80000015;

  clTextCursor           = $80000016;

  clChoiceListBox        = $80000017;

  clUnset		 = $80000018;

  clMenuText             = $80000019;
  clMenuDisabled         = $8000001A;

